server:
  port: 8083

  spring:
    application:
       name: API_GATEWAY


    cloud:
      gateway:
        routes:
          - id: CITIZEN-SERVICE
            uri:
              lb//CITIZEN-SERVICE
        predicate:
          - Path = /citizen/**

          - id: VACCINATION-CENTER-SERVICE
            uri:
              lb//VACCINATION-CENTER-SERVICE
            predicate:
              - Path = /vaccinationcenter/**
